#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Husky https://typicode.github.io/husky/#/
# Git hooks https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

# https://www.devwithimagination.com/2020/04/13/git-commit-hooks-for-branch-naming-using-husky/

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

# HEAD - prevent rebases from failing
# master|develop - prevent main / protected branches (ci) from failing 
valid_branch_regex='^(((fix|feat|refactor|infrastructure|test|tests|docs|ci)\/[a-zA-Z0-9\-]+)|master|develop|HEAD)$'

message="\n\nWrong branch name ("$local_branch_name").\nBranch names should match: $valid_branch_regex. Your commit will be rejected.\n\n"

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi

exit 0